-- ============================================================================
-- v2.0 — Fase 1: tabela de viagens + tabela única de preços + buscas rastreadas
--
-- Rode no SQL Editor do Supabase, na ordem.
-- As tabelas antigas (flight_prices, flight_prices_auto, domestic_prices,
-- domestic_prices_auto) NÃO são apagadas — ficam como backup até validar.
-- ============================================================================

-- ── 1. Viagens ──────────────────────────────────────────────────────────────

create table trips (
  id         bigint generated by default as identity primary key,
  name       text not null,
  period     text not null,                -- ex: "Nov/2026"
  kind       text not null check (kind in ('internacional', 'domestica')),
  date_out   date not null,
  date_back  date not null,
  created_at timestamptz default now()
);

alter table trips enable row level security;
create policy "trips public read"   on trips for select using (true);
create policy "trips auth write"    on trips for all to authenticated using (true) with check (true);
create policy "trips service write" on trips for all to service_role  using (true) with check (true);

insert into trips (id, name, period, kind, date_out, date_back) values
  (1, 'Nova Iorque',          'Nov/2026', 'internacional', '2026-11-19', '2026-11-28'),
  (2, 'Conexão FLN — SP/Rio', 'Nov/2026', 'domestica',     '2026-11-18', '2026-11-29'),
  (3, 'São Paulo',            'Out/2026', 'domestica',     '2026-10-10', '2026-10-11'),
  (4, 'São Paulo',            'Nov/2026', 'domestica',     '2026-10-31', '2026-11-02');

select setval(pg_get_serial_sequence('trips', 'id'), 4);

-- ── 2. Preços (única, substitui as 4 tabelas) ───────────────────────────────

create table prices (
  id          uuid primary key default gen_random_uuid(),
  trip_id     bigint not null references trips(id) on delete cascade,
  date        date not null,
  airline     text not null,               -- texto livre: qualquer companhia
  origin      text not null,
  destination text not null,
  trip_type   text not null default 'round_trip'
              check (trip_type in ('outbound', 'return', 'round_trip')),
  price_out   numeric(10,2),
  price_back  numeric(10,2),
  total       numeric(10,2) generated always as
              (coalesce(price_out, 0) + coalesce(price_back, 0)) stored,
  source      text not null default 'manual' check (source in ('manual', 'auto')),
  notes       text,
  created_at  timestamptz default now(),
  unique (trip_id, date, airline, origin, destination, trip_type, source)
);

create index prices_trip_date_idx on prices (trip_id, date);

alter table prices enable row level security;
create policy "prices public read"   on prices for select using (true);
create policy "prices auth write"    on prices for all to authenticated using (true) with check (true);
create policy "prices service write" on prices for all to service_role  using (true) with check (true);

-- ── 3. Migração dos dados existentes ────────────────────────────────────────

-- Internacional manual → trip 1
insert into prices (trip_id, date, airline, origin, destination, trip_type,
                    price_out, price_back, source, notes, created_at)
select 1, date, airline, origin, destination, 'round_trip',
       price_out, price_back, 'manual', notes, created_at
from flight_prices
on conflict do nothing;

-- Internacional automático → trip 1
insert into prices (trip_id, date, airline, origin, destination, trip_type,
                    price_out, price_back, source, created_at)
select 1, date, airline, origin, destination, 'round_trip',
       price_out, price_back, 'auto', created_at
from flight_prices_auto
on conflict do nothing;

-- Doméstico manual/viagens extras → trips 2, 3, 4
insert into prices (trip_id, date, airline, origin, destination, trip_type,
                    price_out, price_back, source, notes, created_at)
select case trip_name
         when 'novembro_2026' then 2
         when 'sp_outubro'    then 3
         when 'sp_novembro'   then 4
       end,
       date, airline, origin, destination, trip_type,
       price_out, price_back,
       case when trip_name in ('sp_outubro', 'sp_novembro') then 'auto' else 'manual' end,
       notes, created_at
from domestic_prices
on conflict do nothing;

-- Doméstico automático → trip 2
insert into prices (trip_id, date, airline, origin, destination, trip_type,
                    price_out, price_back, source, created_at)
select 2, date, airline, origin, destination, trip_type,
       price_out, price_back, 'auto', created_at
from domestic_prices_auto
on conflict do nothing;

-- ── 4. Buscas rastreadas (config da automação — usada na Fase 2) ────────────

create table tracked_searches (
  id             bigint generated always as identity primary key,
  trip_id        bigint not null references trips(id) on delete cascade,
  api            text not null check (api in ('serpapi', 'talordata', 'rapidapi')),
  airline        text not null,            -- como salvar no banco (ex: 'Gol')
  airline_match  text not null,            -- substring p/ filtrar resposta (ex: 'GOL')
  origin         text not null,            -- sempre na direção da ida
  destination    text not null,
  trip_type      text not null default 'round_trip'
                 check (trip_type in ('outbound', 'return', 'round_trip')),
  max_stops      int  not null default 0,
  outbound_times text,                     -- ex: '4,11'  (ida de manhã)
  return_times   text,                     -- ex: '12,23' (volta tarde/noite)
  active         boolean not null default true,
  created_at     timestamptz default now()
);

alter table tracked_searches enable row level security;
create policy "searches public read"   on tracked_searches for select using (true);
create policy "searches auth write"    on tracked_searches for all to authenticated using (true) with check (true);
create policy "searches service write" on tracked_searches for all to service_role  using (true) with check (true);

-- Trip 1 — Nova Iorque (SerpAPI, round_trip, até 1 conexão)
insert into tracked_searches (trip_id, api, airline, airline_match, origin, destination, trip_type, max_stops) values
  (1, 'serpapi', 'Arajet',   'Arajet',   'GRU', 'EWR', 'round_trip', 1),
  (1, 'serpapi', 'Avianca',  'Avianca',  'GRU', 'IAD', 'round_trip', 1),
  (1, 'serpapi', 'Avianca',  'Avianca',  'GIG', 'IAD', 'round_trip', 1),
  (1, 'serpapi', 'American', 'American', 'GIG', 'JFK', 'round_trip', 1);

-- Trip 2 — Conexão FLN (Talordata round_trip + RapidAPI one-way, diretos)
insert into tracked_searches (trip_id, api, airline, airline_match, origin, destination, trip_type) values
  (2, 'talordata', 'Gol',   'Gol',   'FLN', 'GRU', 'round_trip'),
  (2, 'talordata', 'Latam', 'LATAM', 'FLN', 'GRU', 'round_trip'),
  (2, 'talordata', 'Gol',   'Gol',   'FLN', 'GIG', 'round_trip'),
  (2, 'rapidapi',  'Gol',   'GOL',   'FLN', 'GRU', 'outbound'),
  (2, 'rapidapi',  'Latam', 'LATAM', 'FLN', 'GRU', 'outbound'),
  (2, 'rapidapi',  'Gol',   'GOL',   'FLN', 'GIG', 'outbound'),
  (2, 'rapidapi',  'Gol',   'GOL',   'FLN', 'GRU', 'return'),
  (2, 'rapidapi',  'Latam', 'LATAM', 'FLN', 'GRU', 'return'),
  (2, 'rapidapi',  'Gol',   'GOL',   'FLN', 'GIG', 'return');

-- Trips 3 e 4 — São Paulo CGH (Talordata, ida manhã / volta tarde-noite)
insert into tracked_searches (trip_id, api, airline, airline_match, origin, destination, trip_type, outbound_times, return_times) values
  (3, 'talordata', 'Gol',   'Gol',   'FLN', 'CGH', 'round_trip', '4,11', '12,23'),
  (3, 'talordata', 'Latam', 'LATAM', 'FLN', 'CGH', 'round_trip', '4,11', '12,23'),
  (4, 'talordata', 'Gol',   'Gol',   'FLN', 'CGH', 'round_trip', '4,11', '12,23'),
  (4, 'talordata', 'Latam', 'LATAM', 'FLN', 'CGH', 'round_trip', '4,11', '12,23');

-- ── 5. Conferência ──────────────────────────────────────────────────────────
-- Compare os totais: prices deve ser a soma das 4 tabelas antigas
-- (menos eventuais duplicatas ignoradas pelo on conflict).

select 'flight_prices'        as tabela, count(*) from flight_prices
union all select 'flight_prices_auto',   count(*) from flight_prices_auto
union all select 'domestic_prices',      count(*) from domestic_prices
union all select 'domestic_prices_auto', count(*) from domestic_prices_auto
union all select 'prices (nova)',        count(*) from prices;

select t.name, t.period, p.source, count(*)
from prices p join trips t on t.id = p.trip_id
group by 1, 2, 3
order by 1, 2, 3;
